server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users, /api/users/**
          filters:
            - StripPrefix=1
        #            - name: CircuitBreaker
        #              args:
        #                name: user-service
        #                fallbackUri: forward:/fallback

        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/projects, /api/projects/**
          filters:
            - StripPrefix=1

        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/api/contact, /api/contact/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
